### ISSUE TITLE
Using std::Vec

### ISSUE THREAD

**Issue by Kerollmops** [Kerosene2000/random-wheel-rs#7]
Is this a great idea to use the `std::Vec` collection ?
I didn't realize before but it has a `remove(index: usize)` function then I can use it.
But I need to see the source code to check if it is O(1) in memory or not...

**Comment by Kerollmops** [comment]
https://doc.rust-lang.org/std/vec/struct.Vec.html

**Comment by Kerollmops** [comment]
Owwww, VecDeque is better!
It has `push_front` and `push_back`!
https://doc.rust-lang.org/std/collections/struct.VecDeque.html

**Comment by Kerollmops** [comment]
And `remove` return a `None` in case of an error.

**Comment by Kerollmops** [comment]
I think `VecDeque` is good to be used in this project.
When you see the `Sequences` (the number of actions), it seems good!

https://doc.rust-lang.org/std/collections/

**Comment by uatach** [comment]
Seems interesting! I don't know why I didn't see it when I suggested the others...
But I think it will also need `Clone`, I don't think there's a way of returning something from the weel without being a reference or a copy, and with `remove` we can't return a reference because it will be removed...
In the linked-list, they use a `Raw` type but I couldn't quite understand the magic there yet.

**Comment by Kerollmops** [comment]
Yup, I will test it in some hours, just to know, what is your GMT or just when do you sleep ? (if you sleep 😉)

**Comment by uatach** [comment]
GMT-3, I just woke up.

**Comment by Kerollmops** [comment]
use `VecDeque`.
fixed 6d1ce946eac272e1fcd365c9f8793993d162753a
